### ISSUE TITLE
Is there planned a comment system for the blog?

### ISSUE THREAD

**Issue by MiFrance** [getformwork/formwork#29]
Not a third party service such as Disqus, but integrated with Formwork. Are becoming rarer CMS without database with managing blog comments natively.
Thank to reading ;)

**Comment by giuscris** [comment]
Hi @MiFrance, thank you for the question.
I'm sorry but a native comment system for the blog is not planned since it would be difficult to maintain and would have to deal with spam and potential security issues. So using a third party service is reasonably a better and more secure option.

**Comment by MiFrance** [comment]
Hmm it's a shame :(
Yet with a moderation of comments (optional) and a simple captcha with questions / answers configured in backend, it would do the trick.
The problem with third-party services is that we do not know what they are doing with our data ... No matter if the service closes.
