### ISSUE TITLE
Themes, templates

### ISSUE THREAD

**Issue by aukc1970** [getformwork/formwork#37]
Good day! Is it possible to use additional themes or templates ? If possible the more details as create theme or template ?

**Comment by giuscris** [comment]
Hi @aukc1970 you can have only a theme at a time. You can define templates for the pages you need. I definitely have to write Formwork documentation.
In `templates/` you can find different files which define templates, each one must have a corresponding YAML file in `schemes/` to specify which options they have on the Administration Panel. You can also use partial templates in `templates/partials/` or layouts which define the structure of each page (see `site.php` in `templates/layouts/`).

**Comment by aukc1970** [comment]
Thank you !

**Comment by aukc1970** [comment]
On templates it would be very good if it was possible to connect folders with usual html templates with small edits for example insertion of tags from CMS for the menu for content and others in html template. Fast and easy adaptation of html template to CMS it is very important if it is easy to do it will be a lot of creative templates and then there will be more successful promotion and use of the CMS.
