### ISSUE TITLE
Change or redefine the admin panel address from /admin/ to another ?

### ISSUE THREAD

**Issue by aukc1970** [getformwork/formwork#38]
Good day sometimes for security purposes i need to change or redefine the address of the admin panel. Is it possible in your CMS to change the address of the admin panel to another? If possible, how to change the address of the admin panel from / admin/ to another ? Maybe in the configuration file ?

**Comment by giuscris** [comment]
Thank you for trying Formwork @aukc1970!
I'm sorry it's not possible right now.
I thought it was easy, but just changing .htaccess directives doesn't work. I need to investigate the problem and fix the problem in the next release.

**Comment by aukc1970** [comment]
Thank you !

**Comment by giuscris** [comment]
Now you can use the `admin.root` option right in config/system.yml Thank you again for the request.

**Comment by aukc1970** [comment]
Thanks for the answer ! It would be nice if in the config/system file.yml would be commented out examples of options with description. How to write option admin correctly.root by example ?09.10.2019, 23:20, "Giuseppe Criscione" <notifications@github.com>:Now you can use the admin.root option right in config/system.yml Thank you again for the request.

**Comment by giuscris** [comment]
You can find some information in the [wiki](/getformwork/formwork/wiki/Configuration#admin-options) here on GitHub.

**Comment by aukc1970** [comment]
Thank you ! Good work!10.10.2019, 15:32, "Giuseppe Criscione" <notifications@github.com>:You can find some information in the wiki here on GitHub.

**Comment by aukc1970** [comment]
Good afternoon! Happy New Year and Merry Christmas! I wanted to ask why the submenus in the menu does not work, they do not open and the child items in the menu are not visible. And please tell me how to change the admin folder from admin to another for security, previously this was done in the configuration file and how to remove the tag. You can also ask for instructions on how to adapt the html template to the format cms and the search system in the format cms itself, maybe this can be implemented by a plugin. Thank you in advance!10.10.2019, 07:52, ***@***.***" ***@***.***>:Thanks for the answer ! It would be nice if in the config/system file.yml would be commented out examples of options with description. How to write option admin correctly.root by example ?09.10.2019, 23:20, "Giuseppe Criscione" ***@***.***>:Now you can use the admin.root option right in config/system.yml Thank you again for the request.
