### ISSUE TITLE
Russian language file

### ISSUE THREAD

**Issue by aukc1970** [getformwork/formwork#40]
Good afternoon! Made the translation into Russian here is a link to the file with the translation. If you find errors in the translation, please make a correction.

https://drive.google.com/open?id=14_Z_e_9K9rE23OyK5DRpo1NsuoePY4d0

**Comment by giuscris** [comment]
Thank you @aukc1970 for the interest in Formwork!
I'm glad to hear that new translations are coming for the Administration panel.
Can you make a Pull Request please? I'll directly merge your changes then.

**Comment by aukc1970** [comment]
Good evening ! How to make a pull request?

**Comment by giuscris** [comment]
You'll need to fork the repository first, add the translation file and then create a PR for the main repository. [Here is described how.](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by giuscris** [comment]
Merged in Formwork 1.3.0 ([Changelog](https://github.com/getformwork/formwork/blob/master/CHANGELOG.md#130-2019-11-05)). Thank you again @aukc1970.
