### ISSUE TITLE
CKEditor proposal for the administration panel

### ISSUE THREAD

**Issue by aukc1970** [getformwork/formwork#41]
Good afternoon! Proposal for the editor in the admin panel. I studied the work of CMS very interesting ideas ! Wanted to offer instead editor which is used use editor of CKEditor have him many additional rashireniy plugins that much will simplify and will increase ability to CMS. This editor outputs html code that can be inserted into md files. Here is a link with very interesting plugins such as bootstrap columns and others have the opportunity to try to test.

https://kisameev.ru/javascript/nastroyka-ckeditor-pod-sebya---podklyuchenie-plaginov

**Comment by giuscris** [comment]
Thank you @aukc1970 for the proposal.
I need to do some tests. Markdown output with HTML only if needed should be preferred. As I can read CKEditor 5 can save in Markdown format but I need to see how handles "extra" features. However the focus should always be on the content. Perhaps this editor could be implemented not in the immediate future but as a plugin, but obviously we need a plugin infrastructure first, which I'm already starting to develop.

**Comment by aukc1970** [comment]
It seems to me that the emphasis should not be on md format Markdown this format is very stripped down it will be difficult to do something creative on it. Let the md Markdown format remain but I think it is worth looking at the html format on it you can create more creative pages and a lot of good editors for it.

**Comment by giuscris** [comment]
I understand your point, but that's beyond the scope of the contents of a page. That's on purpose. A page should contain only marked up text, and Markdown is more concise than HTML, all the presentation is handled by the templates. Occasionally you can add some HTML directly in the content (for elements which can't be expressed in Markdown) but that should be avoided. It's up to the templates to decide how a certain element is rendered, i.e. the `.md` files should only contain the semantics.

**Comment by aukc1970** [comment]
Good ! Thanks!

**Comment by giuscris** [comment]
CKEditor could be used as an alternative to the standard CodeMirror editor, just because it's WYSIWYG and it could be preferred by people who understandably don't like writing directly the Markdown syntax.
