### ISSUE TITLE
Functions in configuration files do not work

### ISSUE THREAD

**Issue by aukc1970** [getformwork/formwork#43]
Functions in configuration files do not work
metadata.set_generator: false
generator: Formwork  # Same as `metadata.set_generator` system option

**Comment by giuscris** [comment]
The option `metadata.set_generator` is a boolean that only sets the `generator` meta, which always renders to:

```html
<meta name="generator" content="Formwork">
```

It can be used to expose that the page was rendered by Formwork, not to set the actual value. I'm sorry it's documented wrong, I'll explain better in the Wiki. Thank you for noticing.
