### ISSUE TITLE
There is a very similar Grav CMS what is the difference ?

### ISSUE THREAD

**Issue by aukc1970** [getformwork/formwork#44]
There is a very similar Grav CMS what is the difference ?
https://getgrav.org/
If you make easy adaptation of html templates it will be a big plus. This CMS is very similar to Yours only it is difficult to adapt html templates. The principles are similar md files and config files also uses Symfony.

**Comment by giuscris** [comment]
I'm sorry @aukc1970, I'm not sure I understand the question. What do you mean with "easy adaption of html templates"?

However, the difference with Grav is that Formwork is focused on smaller and simpler sites, which don't require a lot of features and customizations. It's an approach different from other system that may be more useful depending on the situation.

**Comment by aukc1970** [comment]
On html templates here are examples with a simple adaptation of the theme for CMS.
http://get-simple.info/wiki/themes:creation
http://get-simple.info/wiki/themes:tutorial
https://getsimplecms.ru/razrabotchikam/tegi-dlya-shablonov/

**Comment by aukc1970** [comment]
On Grav, too, you can make a small and simple site even without the admin just adding files as here or you can use the ready-made Skeleton Packages this is a ready-configured site. If you in your CMS want to balance the simplicity of the most important and the first thing that it was easy and simple to make themes from ready-made html templates, then you can do a lot of different beautiful sites. The second is the functions the main functions that are needed for the site they can be implemented using plugins.

**Comment by giuscris** [comment]
> It seems to me easy adaptation of html template is when in html template you simply substitute certain tags from CMS and the theme for CMS turns out.
> On html templates here are examples with a simple adaptation of the theme for CMS.

Oh, that's already possible with layouts and partials. I'm sorry I didn't have the time to write a tutorial on how to write templates. But I'll definitely do when possible (see #37).

**Comment by aukc1970** [comment]
Good ! Thanks!

**Comment by giuscris** [comment]
If you need support or want to ask other questions on templates you can join Formwork's chat on Discord https://discord.gg/5Q3BmNY
